sudo: required
dist: trusty
language: generic
install: git clone https://github.com/QubesOS/qubes-builder ~/qubes-builder
script: 
 - ~/qubes-builder/scripts/travis-build
 - travis_wait 30 make -C ~/qubes-builder iso BUILDERCONF=scripts/travis-builder.conf VERBOSE=0 COMPONENTS=installer-qubes-os
after_script:
 - tail -n 1000 ~/qubes-builder/build-logs/installer-qubes-os-iso-*.log
env:
  DIST_DOM0=fc20 INSTALLER_KICKSTART=/tmp/qubes-installer/conf/travis-iso.ks USE_QUBES_REPO_VERSION=3.1
